CREATE TABLE `newhouselog` PARTITIONED BY (`data_date`) STORED AS PARQUET AS
SELECT device_id,
       context_id,
       city_x,
       login_account,
       start_time,
       end_time,
       object_id,
       channel,
       context,
       roomid,
       projecttype,
       modelid,
       projectid,
       shaixuan,
       prj_listid,
       city_y,
       city_name,
       prj_itemname,
       prj_loc,
       prj_decorate,
       prj_views,
       b_lng,
       b_lat,
       price_avg,
       price_show,
       pic_id,
       pic_prjid,
       pic_prjname,
       pic_type,
       pic_desc,
       pic_ting,
       pic_wei,
       pic_chu,
       pic_area,
       pic_sell_point,
       pic_hx_totalprice,
       room_id,
       flats,
       price,
       totalprice,
       data_date
FROM `newhouselog_tmp`



CREATE TABLE `newhouselog_tmp` PARTITIONED BY (`data_date`) STORED AS PARQUET AS
SELECT device_id,
       context_id,
       city_x,
       login_account,
       start_time,
       end_time,
       object_id,
       channel,
       context,
       roomid,
       projecttype,
       modelid,
       projectid,
       shaixuan,
       prj_listid,
       city_y,
       city_name,
       prj_itemname,
       prj_loc,
       prj_decorate,
       prj_views,
       b_lng,
       b_lat,
       price_avg,
       price_show,
       pic_id,
       pic_prjid,
       pic_prjname,
       (CASE pic_type
            WHEN 8 THEN 1
            WHEN 9 THEN 2
            WHEN 10 THEN 3
            WHEN 11 THEN 4
            WHEN 21 THEN 5
            WHEN 22 THEN 6
        END) AS pic_type,
       pic_desc,
       cast(pic_ting AS INT) AS pic_ting,
       pic_wei,
       pic_chu,
       pic_area,
       pic_sell_point,
       cast(ltrim(pic_hx_totalprice, "约") as DOUBLE) as pic_hx_totalprice,
       room_id,
       flats,
       price,
       totalprice,
       data_date
FROM `newhouselog`
-- WHERE pic_hx_totalprice LIKE "约%"
-- LIMIT 10



CREATE TABLE `newhouselog_tmp` PARTITIONED BY (`data_date`) STORED AS PARQUET AS
SELECT device_id,
       context_id,
       city_x,
       login_account,
       start_time,
       end_time,
       object_id,
       channel,
       context,
       roomid,
       projecttype,
       modelid,
       projectid,
       shaixuan,
       prj_listid,
       city_y,
       city_name,
       prj_itemname,
       prj_loc,
       prj_decorate,
       prj_views,
       b_lng,
       b_lat,
       price_avg,
       price_show,
       pic_id,
       pic_prjid,
       pic_prjname,
       pic_type,
       pic_desc,
       pic_ting,
       pic_wei,
       pic_chu,
       pic_area,
       pic_sell_point,
       pic_hx_totalprice,
       room_id,
       flats,
       price,
       totalprice,
       data_date
FROM `newhouselog`


