CREATE TABLE `secondhouse_demo` (
  `DEVICE_ID` text,
  `CONTEXT_ID` text,
  `CITY` text,
  `DATA_DATE` datetime DEFAULT NULL,
  `LOGIN_ACCOUNT` text,
  `START_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `CONTENT` text,
  `OBJECT_ID` text,
  `CONTEXT` text,
  `SECONDHOUSE_ID` text,
  `ESTA_x` text,
  `DISTRICT_x` text,
  `ADDRESS_x` text,
  `STREETID_x` text,
  `BLOCKID` text,
  `ISREAL` text,
  `BLOCKSHOWNAME` text,
  `MRIGHT` text,
  `PURPOSE` text,
  `STRUCTURE` text,
  `BUILDTYPE` text,
  `BUILDYEAR` int(5) DEFAULT NULL,
  `BUILDAREA` double DEFAULT NULL,
  `GARDENAREA` int(5) DEFAULT NULL,
  `SUBFLOOR` int(5) DEFAULT NULL,
  `FLOOR` int(5) DEFAULT NULL,
  `TOTALFLOOR` int(5) DEFAULT NULL,
  `ROOM` int(5) DEFAULT NULL,
  `HALL` int(5) DEFAULT NULL,
  `TOILET` int(5) DEFAULT NULL,
  `KITCHEN` int(5) DEFAULT NULL,
  `BALCONY` int(5) DEFAULT NULL,
  `FORWARD` text,
  `PRICE` int(255) DEFAULT NULL,
  `AVERPRICE_x` double DEFAULT NULL,
  `PRICETERM` text,
  `PRICETYPE` text,
  `BASESERVICE` text,
  `EQUIPMENT` text,
  `ENVIRONMENT` text,
  `TRAFFIC` text,
  `FITMENT` text,
  `SERVERCO` text,
  `CONTACTOR` text,
  `TELNO` text,
  `MOBILE` text,
  `PIC1` text,
  `CREATTIME` text,
  `UPDATETIME` text,
  `EXPIRETIME` text,
  `CITY_NAME` text,
  `BLOCK_ID` text,
  `BLOCKNAME` text,
  `DISTRICT_y` text,
  `STREETID_y` text,
  `AREA` text,
  `ADDRESS_y` text,
  `BUS` text,
  `AVERPRICE_y` double DEFAULT NULL,
  `UPDATEPRICE` text,
  `FORUMID` text,
  `NEWHOUSEID` text,
  `B_MAP_X` text,
  `B_MAP_Y` text,
  `ACCURACY` text,
  `MAP_TEST` text,
  `B_PROPERTY_TYPE` text,
  `B_GREEN` text,
  `B_PARKING` text,
  `B_DEVELOPERS` text,
  `B_PROPERTY_COMPANY` text,
  `B_PROPERTY_FEES` text,
  `B_BUS` text,
  `B_METRO` text,
  `B_NUM` text,
  `BI_S` text,
  `BI_SPELL` text,
  `SUBWAY` text,
  `SITENAME` text,
  `SUBWAYRANGE` text,
  `APP` text,
  `ESTA_y` text,
  `PROPERTY_FEES` text,
  `NOFEE` text,
  `PLOT_RATIO` text,
  `TOTAL_ROOM` text,
  `TURN_TIME` text,
  `B_AREA` text,
  `FEATURE` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8